/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      screens: { md: '768px', lg: '1024px' },
      colors: {
        bg: 'rgb(var(--ios-background) / <alpha-value>)',
        surface: 'rgb(var(--ios-secondary-background) / <alpha-value>)',
        surface2: 'rgb(var(--ios-tertiary-background) / <alpha-value>)',
        section: 'rgb(var(--ios-label) / <alpha-value>)',
        'line-card': '#E0D8CC',
        'line-sidebar': 'rgb(var(--ios-separator) / <alpha-value>)',
        'line-track': 'rgb(var(--ios-fill) / <alpha-value>)',
        'line-streak': 'rgb(var(--ios-separator) / <alpha-value>)',
        ink: {
          50: 'rgb(var(--ios-tertiary-background) / <alpha-value>)',
          100: 'rgb(var(--ios-quaternary-fill) / <alpha-value>)',
          200: 'rgb(var(--ios-separator) / <alpha-value>)',
          300: 'rgb(var(--ios-opaque-separator) / <alpha-value>)',
          400: 'rgb(var(--ios-tertiary-label) / <alpha-value>)',
          500: 'rgb(var(--ios-secondary-label) / <alpha-value>)',
          600: 'rgb(var(--ios-secondary-label) / <alpha-value>)',
          700: 'rgb(var(--ios-label) / <alpha-value>)',
          800: 'rgb(var(--ios-label) / <alpha-value>)',
          900: 'rgb(var(--ios-label) / <alpha-value>)',
        },
        accent: {
          50: '#F0FBF4',
          100: '#D4F0E0',
          200: '#B8EDD0',
          300: '#1A6B38',
          400: '#1A6B38',
          500: '#1A6B38',
          600: '#155830',
          700: '#155830',
        },
        amber: {
          50: '#fff8e1',
          100: '#ffecb3',
          200: '#ffe082',
          300: '#ffca28',
          400: '#ffb300',
          500: '#ff9500',
          600: '#c77700',
          700: '#9a5c00',
          900: '#633b00',
        },
        coral: { 100: '#ffebe8', 300: '#ff6b5e', 400: '#ff453a', 500: '#d70015' },
        fat: { 400: '#ff453a' },
        clay: {
          100: 'rgb(var(--clay-wash) / <alpha-value>)',
          400: 'rgb(var(--clay) / <alpha-value>)',
          500: 'rgb(var(--clay-strong) / <alpha-value>)',
        },
        brand: {
          200: 'rgb(var(--sage-soft) / <alpha-value>)',
          500: 'rgb(var(--sage-ink) / <alpha-value>)',
          600: 'rgb(var(--sage-strong) / <alpha-value>)',
        },
        sky: {
          50: '#e8f5ff',
          100: '#d9f0ff',
          300: '#64d2ff',
          400: '#0a84ff',
          500: '#007aff',
          600: '#0066d6',
        },
      },
      fontFamily: {
        display: ['"DM Serif Display"', 'ui-serif', 'Georgia', 'serif'],
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"DM Sans"',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
        heading: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"DM Sans"',
          'Inter',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
        ],
      },
      borderRadius: {
        none: '0',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        full: '9999px',
        card: '16px',
      },
      transitionDuration: { DEFAULT: '180ms' },
      boxShadow: {
        none: 'none',
        low: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        mid: '0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
        high: '0 8px 24px rgba(0,0,0,0.12), 0 4px 8px rgba(0,0,0,0.06)',
        glow: '0 0 0 3px rgba(26,107,56,0.15)',
        card: '0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
      },
      keyframes: {
        'fade-slide-up': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        wave: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        pop: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
          '100%': { transform: 'scale(1)' },
        },
      },
      animation: {
        'page-in': 'fade-slide-up 0.2s ease-out',
        wave: 'wave 2.2s linear infinite',
        pop: 'pop 0.3s ease-out',
      },
    },
  },
  plugins: [],
};
