import type { ExerciseSmartData, RepRangeByGoal, TrainingGoal } from './exerciseTypes.js';

export function normalizeExerciseName(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function goal(
  muscle_gain: string,
  fat_loss: string,
  endurance: string,
  maintain: string,
  recomp: string,
): Record<TrainingGoal, string> {
  return { muscle_gain, fat_loss, endurance, maintain, recomp };
}

function reps(
  muscle_gain: RepRangeByGoal,
  fat_loss: RepRangeByGoal = { sets: 3, reps: '12-15', rest: 45 },
  endurance: RepRangeByGoal = { sets: 2, reps: '15-20', rest: 30 },
  maintain: RepRangeByGoal = { sets: 3, reps: '8-12', rest: 90 },
  recomp: RepRangeByGoal = { sets: 3, reps: '10-12', rest: 60 },
): Record<TrainingGoal, RepRangeByGoal> {
  return { muscle_gain, fat_loss, endurance, maintain, recomp };
}

function e(partial: ExerciseSmartData & { matchKeys?: string[] }): ExerciseSmartData {
  return partial;
}

/** Curated smart metadata for core exercises (matched to wger names via normalize + matchKeys). */
export const CURATED_EXERCISES: (ExerciseSmartData & { matchKeys?: string[] })[] = [
  // Chest / Push
  e({
    wgerName: 'Bench Press',
    matchKeys: ['barbell bench press', 'bench press barbell'],
    movementPattern: 'push',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['pectoralis major'], secondary: ['anterior deltoid', 'triceps'] },
    hypertrophyRating: 10,
    fatLossRating: 7,
    enduranceRating: 5,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Heavy horizontal loading for overall chest thickness and pressing strength.',
    goalExplanation: goal(
      'Allows progressive overload on the largest chest fibers with stable bar path.',
      'Large muscle recruitment elevates post-workout calorie burn.',
      'Moderate loads for high reps build pressing endurance.',
      'Maintains upper-body strength with moderate volume.',
      'Balances strength and metabolic demand for body recomposition.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: '6-10', rest: 120 },
      { sets: 3, reps: '10-12', rest: 60 },
    ),
    rotationGroup: 'horizontal-push-heavy',
  }),
  e({
    wgerName: 'Dumbbell Bench Press',
    matchKeys: ['benchpress dumbbells', 'dumbbell bench press'],
    movementPattern: 'push',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['pectoralis major'], secondary: ['anterior deltoid', 'triceps'] },
    hypertrophyRating: 9,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Independent arm path increases stretch at the bottom and stabilizer demand.',
    goalExplanation: goal(
      'Greater ROM at the bottom emphasizes stretch-mediated hypertrophy.',
      'Unilateral stabilization increases energy expenditure.',
      'Lighter loads allow higher rep density safely.',
      'Joint-friendly option to preserve chest volume.',
      'Pairs well with barbell work for full ROM chest development.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '8-12', rest: 90 }),
    rotationGroup: 'horizontal-push-heavy',
  }),
  e({
    wgerName: 'Incline Bench Press - Barbell',
    matchKeys: ['incline barbell press', 'incline bench press barbell'],
    movementPattern: 'push',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['upper pectoralis major'], secondary: ['anterior deltoid', 'triceps'] },
    hypertrophyRating: 9,
    fatLossRating: 7,
    enduranceRating: 5,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Targets clavicular head of pecs better than flat pressing.',
    goalExplanation: goal(
      'Builds upper chest shelf for balanced physique.',
      'Compound incline work supports fat-loss training density.',
      'Moderate endurance stimulus for shoulders and chest.',
      'Maintains upper chest thickness.',
      'Upper chest emphasis improves recomp upper-body shape.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-10', rest: 120 }),
    rotationGroup: 'upper-chest-compound',
  }),
  e({
    wgerName: 'Incline Bench Press - Dumbbell',
    matchKeys: ['incline dumbbell press', 'incline bench press dumbbell'],
    movementPattern: 'push',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['upper pectoralis major'], secondary: ['anterior deltoid', 'triceps'] },
    hypertrophyRating: 9,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Combines incline angle with dumbbell stretch for upper chest isolation within a compound.',
    goalExplanation: goal(
      'Excellent upper chest hypertrophy with reduced shoulder stress vs barbell.',
      'Higher rep incline dumbbell work adds metabolic cost.',
      'Supports muscular endurance in pressing patterns.',
      'Sustainable upper chest maintenance lift.',
      'Fills upper chest gaps during recomp phases.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 90 }),
    rotationGroup: 'upper-chest-compound',
  }),
  e({
    wgerName: 'Cable Fly',
    matchKeys: ['cable fly', 'cable flye', 'bent over cable flye', 'fly with cable'],
    movementPattern: 'isolation',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['pectoralis major'], secondary: ['anterior deltoid'] },
    hypertrophyRating: 8,
    fatLossRating: 6,
    enduranceRating: 7,
    timeRequired: 3,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Constant tension through horizontal adduction — peak contraction focus.',
    goalExplanation: goal(
      'Isolates pecs after compounds for metabolic stress and pump.',
      'Light continuous tension suits circuit-style fat loss.',
      'High-rep flyes build local muscular endurance.',
      'Low-joint-stress chest finisher.',
      'Adds chest detail without heavy axial loading.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '12-15', rest: 60 },
      { sets: 3, reps: '15-20', rest: 45 },
    ),
    rotationGroup: 'chest-isolation-mid',
  }),
  e({
    wgerName: 'Pec Deck',
    matchKeys: ['pec deck', 'butterfly', 'machine fly'],
    movementPattern: 'isolation',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['pectoralis major'], secondary: [] },
    hypertrophyRating: 7,
    fatLossRating: 6,
    enduranceRating: 7,
    timeRequired: 3,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Guided path isolates pecs with minimal technique demand.',
    goalExplanation: goal(
      'Safe pec isolation for beginners and finisher sets.',
      'Machine stability allows rapid supersets.',
      'High reps build chest endurance.',
      'Easy to auto-regulate for maintenance.',
      'Adds chest volume with low systemic fatigue.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '12-15', rest: 60 }),
    rotationGroup: 'chest-isolation-mid',
  }),
  e({
    wgerName: 'Decline Bench Press Barbell',
    matchKeys: ['decline bench press barbell', 'decline bench press dumbbell', 'decline press'],
    movementPattern: 'push',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['lower pectoralis major'], secondary: ['triceps', 'anterior deltoid'] },
    hypertrophyRating: 8,
    fatLossRating: 6,
    enduranceRating: 5,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Emphasizes sternal/lower pec fibers often undertrained on flat bench.',
    goalExplanation: goal(
      'Develops lower chest fullness for complete pec development.',
      'Compound decline work adds training volume.',
      'Moderate load endurance pressing.',
      'Maintains lower chest thickness.',
      'Balances upper/flat work in recomp splits.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 90 }),
    rotationGroup: 'lower-chest',
  }),
  e({
    wgerName: 'Push Up',
    matchKeys: ['push up', 'push-up', 'pushups', 'dumbbell push up', 'deficit push ups'],
    movementPattern: 'push',
    workoutSplit: ['chest', 'push', 'upper'],
    musclesFocused: { primary: ['pectoralis major'], secondary: ['triceps', 'core'] },
    hypertrophyRating: 7,
    fatLossRating: 8,
    enduranceRating: 9,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Bodyweight horizontal push scalable anywhere with core integration.',
    goalExplanation: goal(
      'High rep push-ups accumulate chest volume with low equipment needs.',
      'Excellent for circuits and conditioning blocks.',
      'Builds pressing endurance and core stability.',
      'Minimal setup maintenance movement.',
      'Accessible volume for recomp at home or gym.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: 'AMRAP', rest: 60 },
      { sets: 3, reps: '15-25', rest: 45 },
      { sets: 3, reps: '20-30', rest: 30 },
    ),
    rotationGroup: 'horizontal-push-bodyweight',
  }),
  e({
    wgerName: 'Overhead Press',
    matchKeys: ['military press', 'barbell shoulder press', 'standing overhead press'],
    movementPattern: 'push',
    workoutSplit: ['shoulders', 'push', 'upper'],
    musclesFocused: { primary: ['anterior deltoid', 'medial deltoid'], secondary: ['triceps', 'upper traps'] },
    hypertrophyRating: 9,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Primary vertical pressing pattern for shoulder mass and overhead strength.',
    goalExplanation: goal(
      'Builds capped shoulders and triceps with heavy vertical load.',
      'Standing variant increases core and calorie demand.',
      'Moderate reps develop pressing stamina.',
      'Maintains overhead strength long term.',
      'Shoulder development for balanced recomp physique.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-10', rest: 120 }),
    rotationGroup: 'vertical-push-heavy',
  }),
  e({
    wgerName: 'Single-arm dumbbell shoulder press',
    matchKeys: ['dumbbell shoulder press', 'arnold shoulder press', 'seated dumbbell shoulder press'],
    movementPattern: 'push',
    workoutSplit: ['shoulders', 'push', 'upper'],
    musclesFocused: { primary: ['medial deltoid', 'anterior deltoid'], secondary: ['triceps'] },
    hypertrophyRating: 8,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Free dumbbell path allows natural shoulder rotation and ROM.',
    goalExplanation: goal(
      'Shoulder hypertrophy with reduced impingement vs fixed bar path.',
      'Unilateral stabilization increases energy cost.',
      'Higher rep shoulder endurance work.',
      'Joint-friendly shoulder maintenance.',
      'Adds shoulder volume during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 90 }),
    rotationGroup: 'vertical-push-heavy',
  }),
  e({
    wgerName: 'Lateral Raise',
    matchKeys: ['45 lateral raises', 'cable lateral raise', 'side lateral raise'],
    movementPattern: 'isolation',
    workoutSplit: ['shoulders', 'push', 'upper'],
    musclesFocused: { primary: ['medial deltoid'], secondary: ['upper traps'] },
    hypertrophyRating: 9,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Primary medial delt builder — width of shoulders.',
    goalExplanation: goal(
      'Essential for capped, wide shoulders.',
      'Light isolation suits high-rep finishers.',
      'Builds shoulder endurance for sports.',
      'Low fatigue shoulder maintenance.',
      'Shoulder width improves V-taper during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: '12-20', rest: 45 },
      { sets: 3, reps: '15-20', rest: 30 },
    ),
    rotationGroup: 'medial-delt-isolation',
  }),
  e({
    wgerName: 'Front Raises',
    matchKeys: ['front raise', 'cable front raise', 'front raise cable', 'dumbbell front raise'],
    movementPattern: 'isolation',
    workoutSplit: ['shoulders', 'push', 'upper'],
    musclesFocused: { primary: ['anterior deltoid'], secondary: [] },
    hypertrophyRating: 6,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Isolates anterior delt when overhead pressing volume is limited.',
    goalExplanation: goal(
      'Targets front delt without heavy pressing stress.',
      'Light front raises fit metabolic circuits.',
      'High rep anterior delt endurance.',
      'Balances rear-delt emphasis in programs.',
      'Fine-tunes shoulder balance during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '12-15', rest: 45 }),
    rotationGroup: 'anterior-delt-isolation',
  }),
  e({
    wgerName: 'Triceps Pushdown',
    matchKeys: ['tricep pushdown', 'triceps pushdown', 'cable pushdown', 'rocking triceps pushdown'],
    movementPattern: 'isolation',
    workoutSplit: ['arms', 'push', 'upper'],
    musclesFocused: { primary: ['triceps brachii'], secondary: [] },
    hypertrophyRating: 8,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Constant cable tension isolates triceps through full extension.',
    goalExplanation: goal(
      'Direct triceps volume for arm size.',
      'Quick isolation for pump in fat-loss phases.',
      'High rep pushdowns build arm endurance.',
      'Low-stress triceps maintenance.',
      'Arm detail for recomp aesthetics.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-15', rest: 60 }),
    rotationGroup: 'tricep-isolation',
  }),
  e({
    wgerName: 'Skullcrusher SZ-bar',
    matchKeys: ['skull crusher', 'skullcrusher', 'floor skull crusher', 'skullcrusher dumbbells'],
    movementPattern: 'isolation',
    workoutSplit: ['arms', 'push', 'upper'],
    musclesFocused: { primary: ['triceps long head'], secondary: [] },
    hypertrophyRating: 8,
    fatLossRating: 5,
    enduranceRating: 6,
    timeRequired: 3,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Stretch under load emphasizes long head of triceps.',
    goalExplanation: goal(
      'Long-head triceps development for arm horseshoe shape.',
      'Moderate isolation volume.',
      'Moderate rep endurance for elbows.',
      'Maintain triceps size with moderate load.',
      'Arm hypertrophy support during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 90 }),
    rotationGroup: 'tricep-isolation',
  }),
  e({
    wgerName: 'Close Grip Bench Press',
    matchKeys: ['close grip bench', 'bench press narrow grip', 'narrow grip bench press'],
    movementPattern: 'push',
    workoutSplit: ['arms', 'chest', 'push', 'upper'],
    musclesFocused: { primary: ['triceps brachii'], secondary: ['pectoralis major', 'anterior deltoid'] },
    hypertrophyRating: 8,
    fatLossRating: 6,
    enduranceRating: 5,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Heavy compound triceps overload while still loading chest.',
    goalExplanation: goal(
      'Builds pressing strength and triceps mass together.',
      'Compound movement for arm/chest density.',
      'Moderate endurance pressing pattern.',
      'Maintains triceps strength on bench variations.',
      'Efficient arm compound during recomp.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-10', rest: 120 }),
    rotationGroup: 'tricep-compound',
  }),
  // Back / Pull
  e({
    wgerName: 'Pull-ups',
    matchKeys: ['pull up', 'pull-up', 'pullup', 'assisted pull-up', 'archer pull up'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['latissimus dorsi'], secondary: ['biceps', 'rear deltoid'] },
    hypertrophyRating: 9,
    fatLossRating: 8,
    enduranceRating: 8,
    timeRequired: 3,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Bodyweight vertical pull — gold standard lat width builder.',
    goalExplanation: goal(
      'Progressive pull-up volume drives lat hypertrophy.',
      'Compound bodyweight pull elevates heart rate in circuits.',
      'High rep sets build grip and pulling endurance.',
      'Maintains back strength with minimal equipment.',
      'Efficient back volume for recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: '6-12', rest: 120 },
      { sets: 3, reps: 'AMRAP', rest: 60 },
    ),
    rotationGroup: 'vertical-pull-bodyweight',
  }),
  e({
    wgerName: 'Wide-grip supinated lat pulldown',
    matchKeys: ['lat pulldown', 'close-grip supinated lat pulldown', 'lat pull down straight back'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['latissimus dorsi'], secondary: ['biceps', 'rear deltoid'] },
    hypertrophyRating: 8,
    fatLossRating: 7,
    enduranceRating: 7,
    timeRequired: 3,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Scalable vertical pull for users not yet doing pull-ups.',
    goalExplanation: goal(
      'Loadable lat hypertrophy with adjustable weight.',
      'Machine stability suits supersets and drop sets.',
      'High rep pulldowns build back endurance.',
      'Accessible back maintenance movement.',
      'Lat volume without pull-up prerequisite.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '8-12', rest: 90 }),
    rotationGroup: 'vertical-pull-machine',
  }),
  e({
    wgerName: 'Barbell Row (Underhand)',
    matchKeys: ['barbell row overhand', 'barbell row', 'bent over barbell row', 'pendlay row'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['latissimus dorsi', 'rhomboids'], secondary: ['biceps', 'rear deltoid'] },
    hypertrophyRating: 9,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Heavy horizontal pull for mid-back thickness and lat overload.',
    goalExplanation: goal(
      'Builds dense back mass with progressive rowing load.',
      'Compound row adds metabolic demand.',
      'Moderate rep rows for back stamina.',
      'Maintains rowing strength.',
      'Back thickness for recomp upper body.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-10', rest: 120 }),
    rotationGroup: 'horizontal-pull-heavy',
  }),
  e({
    wgerName: 'Bent Over Dumbbell Rows',
    matchKeys: ['dumbbell row', 'single arm dumbbell row', 'one arm row'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['latissimus dorsi'], secondary: ['biceps', 'rear deltoid'] },
    hypertrophyRating: 8,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 3,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Unilateral row fixes asymmetries and increases ROM per side.',
    goalExplanation: goal(
      'Single-arm rows allow deep stretch and heavy per-side load.',
      'Alternating rows fit fat-loss circuits.',
      'Moderate endurance pulling.',
      'Joint-friendly back maintenance.',
      'Balanced back development during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 90 }),
    rotationGroup: 'horizontal-pull-heavy',
  }),
  e({
    wgerName: 'Seated Cable Row',
    matchKeys: ['cable row', 'low row'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['rhomboids', 'middle traps'], secondary: ['latissimus dorsi', 'biceps'] },
    hypertrophyRating: 8,
    fatLossRating: 6,
    enduranceRating: 7,
    timeRequired: 3,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Stable seated path emphasizes mid-back squeeze and scapular retraction.',
    goalExplanation: goal(
      'Mid-back hypertrophy with controlled tempo.',
      'Steady cable tension for pump work.',
      'High rep rows build back endurance.',
      'Low-skill back maintenance.',
      'Mid-back detail for posture and recomp.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '10-12', rest: 75 }),
    rotationGroup: 'horizontal-pull-cable',
  }),
  e({
    wgerName: 'Dumbbell Bent Over Face Pull',
    matchKeys: ['face pull', 'cable face pull', 'face pulls with yellow green band'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'shoulders', 'pull', 'upper'],
    musclesFocused: { primary: ['rear deltoid', 'external rotators'], secondary: ['rhomboids', 'middle traps'] },
    hypertrophyRating: 7,
    fatLossRating: 5,
    enduranceRating: 8,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Simultaneously targets rear delts and external rotators for shoulder health.',
    goalExplanation: goal(
      'Rear delt and rotator cuff volume for balanced shoulders.',
      'Light high-rep face pulls in warm-ups or finishers.',
      'Excellent endurance for upper back and rotators.',
      'Shoulder health maintenance staple.',
      'Posture and shoulder balance during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '15-20', rest: 45 },
      { sets: 3, reps: '20-25', rest: 30 },
    ),
    rotationGroup: 'rear-delt-isolation',
  }),
  e({
    wgerName: 'Straight-Arm Pulldown (Cable)',
    matchKeys: ['straight arm pulldown', 'side straight arm pulldown cable', 'straight-arm pull down'],
    movementPattern: 'isolation',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['latissimus dorsi'], secondary: [] },
    hypertrophyRating: 7,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Lat isolation without biceps takeover — pure shoulder extension.',
    goalExplanation: goal(
      'Mind-muscle lat connection and width emphasis.',
      'Light isolation for metabolic back work.',
      'High rep lat endurance.',
      'Low elbow stress lat maintenance.',
      'Lat detail without heavy rowing.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '12-15', rest: 60 }),
    rotationGroup: 'lat-isolation',
  }),
  e({
    wgerName: 'Chin Up',
    matchKeys: ['chin-up', 'chinup', 'assisted chin'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'pull', 'upper', 'arms'],
    musclesFocused: { primary: ['latissimus dorsi', 'biceps'], secondary: ['brachialis'] },
    hypertrophyRating: 9,
    fatLossRating: 8,
    enduranceRating: 8,
    timeRequired: 3,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Supinated grip increases biceps contribution vs pull-ups.',
    goalExplanation: goal(
      'Back and biceps hypertrophy in one movement.',
      'Bodyweight density for fat-loss training.',
      'Grip and pull endurance builder.',
      'Maintains back/biceps strength.',
      'Efficient pull pattern for recomp.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-12', rest: 120 }),
    rotationGroup: 'vertical-pull-supinated',
  }),
  e({
    wgerName: 'Rowing, T-bar',
    matchKeys: ['t bar row', 't-bar row', 'rowing t bar', 'landmine row'],
    movementPattern: 'pull',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['latissimus dorsi', 'middle traps'], secondary: ['biceps', 'rear deltoid'] },
    hypertrophyRating: 9,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Fixed arc allows heavy rowing with strong lat stretch.',
    goalExplanation: goal(
      'Heavy back thickness with stable loading.',
      'Compound row for training density.',
      'Moderate rep back endurance.',
      'Maintains rowing overload.',
      'Back mass for recomp.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-10', rest: 120 }),
    rotationGroup: 'horizontal-pull-heavy',
  }),
  e({
    wgerName: 'Shoulder Shrug',
    matchKeys: ['shrug', 'barbell shrug', 'barbell silverback shrug', 'shrugs barbells', 'cable shrug in'],
    movementPattern: 'isolation',
    workoutSplit: ['back', 'pull', 'upper'],
    musclesFocused: { primary: ['upper traps'], secondary: ['levator scapulae'] },
    hypertrophyRating: 7,
    fatLossRating: 4,
    enduranceRating: 6,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Direct upper trap elevation for neck/upper back aesthetics.',
    goalExplanation: goal(
      'Trap hypertrophy for complete back development.',
      'Light shrug volume in finishers.',
      'Moderate trap endurance.',
      'Maintains trap size.',
      'Upper back detail during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '12-15', rest: 60 }),
    rotationGroup: 'trap-isolation',
  }),
  e({
    wgerName: 'Biceps Curls With Barbell',
    matchKeys: ['barbell curl', 'biceps curl barbell', 'standing barbell curl'],
    movementPattern: 'isolation',
    workoutSplit: ['arms', 'pull', 'upper'],
    musclesFocused: { primary: ['biceps brachii'], secondary: ['brachialis'] },
    hypertrophyRating: 8,
    fatLossRating: 5,
    enduranceRating: 6,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Classic heavy biceps overload with bilateral stability.',
    goalExplanation: goal(
      'Progressive biceps loading for arm size.',
      'Moderate isolation in arm circuits.',
      'Rep endurance for elbow flexors.',
      'Maintains arm size.',
      'Arm hypertrophy during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 75 }),
    rotationGroup: 'bicep-compound',
  }),
  e({
    wgerName: 'Dumbbell Curl',
    matchKeys: ['alternating biceps curls', 'standing dumbbell curl'],
    movementPattern: 'isolation',
    workoutSplit: ['arms', 'pull', 'upper'],
    musclesFocused: { primary: ['biceps brachii'], secondary: [] },
    hypertrophyRating: 8,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Alternating curls allow supination focus and unilateral correction.',
    goalExplanation: goal(
      'Arm hypertrophy with natural wrist rotation.',
      'Alternating pattern suits supersets.',
      'High rep curl endurance.',
      'Easy arm maintenance.',
      'Arm volume for recomp aesthetics.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-12', rest: 60 }),
    rotationGroup: 'bicep-compound',
  }),
  e({
    wgerName: 'Hammer Curls',
    matchKeys: ['hammer curl', 'dumbbell hammer curl', 'alternating dumbbell hammer curl', 'neutral grip curl'],
    movementPattern: 'isolation',
    workoutSplit: ['arms', 'pull', 'upper'],
    musclesFocused: { primary: ['brachialis', 'brachioradialis'], secondary: ['biceps brachii'] },
    hypertrophyRating: 7,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Neutral grip builds arm thickness via brachialis — distinct from supinated curls.',
    goalExplanation: goal(
      'Arm width and brachialis development.',
      'Light hammer curls in arm finishers.',
      'Forearm and arm endurance.',
      'Maintains arm thickness.',
      'Completes arm development in recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-12', rest: 60 }),
    rotationGroup: 'brachialis-isolation',
  }),
  e({
    wgerName: 'Incline Dumbbell Curl',
    matchKeys: ['dumbbell incline curl'],
    movementPattern: 'isolation',
    workoutSplit: ['arms', 'pull', 'upper'],
    musclesFocused: { primary: ['biceps long head'], secondary: [] },
    hypertrophyRating: 8,
    fatLossRating: 5,
    enduranceRating: 6,
    timeRequired: 2,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Incline angle pre-stretches long head for unique hypertrophy stimulus.',
    goalExplanation: goal(
      'Long-head biceps emphasis for peak development.',
      'Stretch-focused curl for arm detail.',
      'Moderate rep arm endurance.',
      'Maintains long-head size.',
      'Arm shape refinement during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-12', rest: 60 }),
    rotationGroup: 'bicep-stretch-isolation',
  }),
  e({
    wgerName: 'Preacher Curl',
    matchKeys: ['preacher curl externally rotated', 'preacher curl internally rotated', 'preacher curls', 'scott curl'],
    movementPattern: 'isolation',
    workoutSplit: ['arms', 'pull', 'upper'],
    musclesFocused: { primary: ['biceps short head'], secondary: [] },
    hypertrophyRating: 8,
    fatLossRating: 5,
    enduranceRating: 6,
    timeRequired: 2,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Arm pad eliminates swing — peak contraction on short head.',
    goalExplanation: goal(
      'Short-head peak and arm height.',
      'Strict curl for controlled arm volume.',
      'Moderate endurance with fixed elbow.',
      'Maintains arm peak.',
      'Arm detail for recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 75 }),
    rotationGroup: 'bicep-peak-isolation',
  }),
  // Legs
  e({
    wgerName: 'Barbell Full Squat',
    matchKeys: ['back squat', 'barbell squat', 'squat barbell'],
    movementPattern: 'squat',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings', 'core'] },
    hypertrophyRating: 10,
    fatLossRating: 9,
    enduranceRating: 6,
    timeRequired: 5,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'King of lower-body compounds — systemic growth and strength driver.',
    goalExplanation: goal(
      'Maximum leg hypertrophy and hormonal response from heavy squats.',
      'High calorie burn from large muscle mass recruitment.',
      'Moderate rep squats build leg stamina.',
      'Maintains lower-body strength baseline.',
      'Leg mass driver for recomp.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-10', rest: 150 }),
    rotationGroup: 'quad-dominant-heavy',
  }),
  e({
    wgerName: 'Front Squats',
    matchKeys: ['front squat', 'barbell front squat', 'double kettlebell front squat', 'dumbbell front squat'],
    movementPattern: 'squat',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['quadriceps'], secondary: ['gluteus maximus', 'core'] },
    hypertrophyRating: 9,
    fatLossRating: 8,
    enduranceRating: 6,
    timeRequired: 5,
    difficulty: 'advanced',
    jointFriendly: false,
    uniqueMuscleContribution: 'Upright torso shifts emphasis to quads and core vs back squat.',
    goalExplanation: goal(
      'Quad-dominant squat variation for knee-extensor hypertrophy.',
      'Front rack increases core demand and calorie burn.',
      'Moderate endurance squat pattern.',
      'Maintains quad strength with upright posture.',
      'Quad emphasis during recomp leg days.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '6-10', rest: 150 }),
    rotationGroup: 'quad-dominant-heavy',
  }),
  e({
    wgerName: 'Leg Press',
    matchKeys: ['45 leg press', 'sled leg press'],
    movementPattern: 'squat',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings'] },
    hypertrophyRating: 8,
    fatLossRating: 8,
    enduranceRating: 7,
    timeRequired: 4,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'High quad volume with reduced spinal loading vs free-weight squats.',
    goalExplanation: goal(
      'Leg hypertrophy with safer loading for high volume.',
      'High rep leg press suits fat-loss leg circuits.',
      'Endurance sets build quad stamina.',
      'Joint-friendly leg maintenance.',
      'Leg volume without back fatigue during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: '10-15', rest: 90 },
      { sets: 3, reps: '15-20', rest: 60 },
    ),
    rotationGroup: 'quad-dominant-machine',
  }),
  e({
    wgerName: 'Barbell Romanian Deadlift (RDL)',
    matchKeys: ['romanian deadlift', 'rdl', 'stiff leg deadlift'],
    movementPattern: 'hinge',
    workoutSplit: ['legs', 'lower', 'pull'],
    musclesFocused: { primary: ['hamstrings', 'gluteus maximus'], secondary: ['erector spinae'] },
    hypertrophyRating: 9,
    fatLossRating: 8,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Eccentric hamstring stretch under load — posterior chain staple.',
    goalExplanation: goal(
      'Hamstring and glute hypertrophy with hip hinge pattern.',
      'Large posterior chain recruitment for calorie burn.',
      'Moderate rep RDLs for hinge endurance.',
      'Maintains hamstring length and strength.',
      'Posterior chain for recomp leg balance.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 90 }),
    rotationGroup: 'hamstring-dominant-hinge',
  }),
  e({
    wgerName: 'Leg Curl',
    matchKeys: ['leg curls', 'lying leg curl', 'seated leg curl'],
    movementPattern: 'isolation',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['hamstrings'], secondary: [] },
    hypertrophyRating: 7,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Direct knee-flexion isolation when hip hinges are limited.',
    goalExplanation: goal(
      'Hamstring isolation to balance quad-dominant leg work.',
      'Light curl finishers in leg circuits.',
      'High rep hamstring endurance.',
      'Low-skill hamstring maintenance.',
      'Hamstring detail during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-15', rest: 60 }),
    rotationGroup: 'hamstring-isolation',
  }),
  e({
    wgerName: 'Leg Extension',
    matchKeys: ['leg extensions', 'beinstrecker'],
    movementPattern: 'isolation',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['quadriceps'], secondary: [] },
    hypertrophyRating: 7,
    fatLossRating: 5,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: false,
    uniqueMuscleContribution: 'Pure quad isolation — rectus femoris emphasis at terminal extension.',
    goalExplanation: goal(
      'Quad detail and pre-exhaust before compounds.',
      'High rep extensions for leg pump work.',
      'Quad endurance for sports.',
      'Maintains quad definition.',
      'Quad refinement during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '12-15', rest: 60 }),
    rotationGroup: 'quad-isolation',
  }),
  e({
    wgerName: 'Hip Thrust',
    matchKeys: ['barbell hip thrust', 'hip thrust barbell'],
    movementPattern: 'hinge',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['gluteus maximus'], secondary: ['hamstrings'] },
    hypertrophyRating: 9,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Peak glute contraction at lockout — best glute max overload.',
    goalExplanation: goal(
      'Primary glute hypertrophy movement.',
      'Heavy hip thrusts add lower-body training density.',
      'Moderate rep glute endurance.',
      'Maintains glute strength and shape.',
      'Glute development for recomp lower body.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '8-12', rest: 90 }),
    rotationGroup: 'glute-dominant',
  }),
  e({
    wgerName: 'Glute Bridge',
    matchKeys: ['single leg glute bridge', 'bodyweight glute bridge'],
    movementPattern: 'hinge',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['gluteus maximus'], secondary: ['hamstrings'] },
    hypertrophyRating: 7,
    fatLossRating: 7,
    enduranceRating: 8,
    timeRequired: 3,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Accessible glute activation pattern — gateway to hip thrust loading.',
    goalExplanation: goal(
      'Glute volume with low spinal stress.',
      'Bodyweight bridges in warm-ups and circuits.',
      'High rep glute endurance.',
      'Easy glute maintenance anywhere.',
      'Glute activation during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '12-15', rest: 60 },
      { sets: 3, reps: '15-20', rest: 45 },
    ),
    rotationGroup: 'glute-dominant',
  }),
  e({
    wgerName: 'Dumbbell Lunges Walking',
    matchKeys: ['walking lunge', 'barbell lunges walking', 'dumbbell walking lunge', 'walking lunges'],
    movementPattern: 'squat',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings'] },
    hypertrophyRating: 8,
    fatLossRating: 8,
    enduranceRating: 8,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Dynamic unilateral leg work with balance and coordination demand.',
    goalExplanation: goal(
      'Unilateral quad/glute hypertrophy and symmetry.',
      'Walking lunges elevate heart rate significantly.',
      'High rep lunges build leg endurance.',
      'Functional leg maintenance.',
      'Unilateral leg work for recomp balance.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-12 each', rest: 90 }),
    rotationGroup: 'quad-unilateral',
  }),
  e({
    wgerName: 'Bulgarian Squat with Dumbbells',
    matchKeys: ['bulgarian split squat', 'rear foot elevated split squat', 'bulgarian split squats'],
    movementPattern: 'squat',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings'] },
    hypertrophyRating: 9,
    fatLossRating: 8,
    enduranceRating: 7,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Deep single-leg squat — maximal unilateral quad/glute overload.',
    goalExplanation: goal(
      'Single-leg hypertrophy without spinal load.',
      'Metabolic unilateral leg training.',
      'Moderate endurance per leg.',
      'Maintains single-leg strength.',
      'Fixes leg imbalances during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12 each', rest: 90 }),
    rotationGroup: 'quad-unilateral',
  }),
  e({
    wgerName: 'Standing Calf Raises',
    matchKeys: ['calf raise', 'standing calf raise', 'smith machine calf raise'],
    movementPattern: 'isolation',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['gastrocnemius'], secondary: ['soleus'] },
    hypertrophyRating: 7,
    fatLossRating: 4,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Standing position targets gastrocnemius for calf peak.',
    goalExplanation: goal(
      'Calf hypertrophy for complete leg development.',
      'Light calf work in finishers.',
      'High rep calf endurance.',
      'Maintains calf size.',
      'Lower leg detail during recomp.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '12-15', rest: 45 }),
    rotationGroup: 'calf-isolation',
  }),
  e({
    wgerName: 'Seated Calf Raise',
    matchKeys: ['seated dumbbell calf raise', 'seated calf raises'],
    movementPattern: 'isolation',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['soleus'], secondary: ['gastrocnemius'] },
    hypertrophyRating: 6,
    fatLossRating: 4,
    enduranceRating: 8,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Bent knee isolates soleus — complements standing calf work.',
    goalExplanation: goal(
      'Soleus development for complete calf mass.',
      'Light seated raises in leg finishers.',
      'High rep soleus endurance.',
      'Maintains lower calf thickness.',
      'Calf balance during recomp.',
    ),
    repRangeByGoal: reps({ sets: 4, reps: '15-20', rest: 45 }),
    rotationGroup: 'calf-isolation',
  }),
  e({
    wgerName: 'Sumo Squats',
    matchKeys: ['sumo squat', 'squat sumo', 'dumbbell sumo squat'],
    movementPattern: 'squat',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['adductors', 'gluteus maximus', 'quadriceps'], secondary: ['hamstrings'] },
    hypertrophyRating: 8,
    fatLossRating: 7,
    enduranceRating: 6,
    timeRequired: 4,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Wide stance emphasizes adductors and inner quad/glute line.',
    goalExplanation: goal(
      'Inner thigh and glute development from wide stance.',
      'Compound leg work with hip variety.',
      'Moderate leg endurance.',
      'Maintains hip mobility and leg strength.',
      'Leg variety during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 90 }),
    rotationGroup: 'inner-quad-glute',
  }),
  e({
    wgerName: 'Step-ups',
    matchKeys: ['step up', 'step-up', 'dumbbell step up', 'weighted step-ups', 'box step up'],
    movementPattern: 'squat',
    workoutSplit: ['legs', 'lower'],
    musclesFocused: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['hamstrings'] },
    hypertrophyRating: 7,
    fatLossRating: 8,
    enduranceRating: 8,
    timeRequired: 3,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Functional unilateral step pattern — knee-friendly quad work.',
    goalExplanation: goal(
      'Unilateral quad/glute volume with low skill floor.',
      'Step-ups fit cardio-strength circuits.',
      'High rep step endurance.',
      'Functional leg maintenance.',
      'Accessible unilateral work for recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-12 each', rest: 60 }),
    rotationGroup: 'quad-unilateral',
  }),
  e({
    wgerName: 'Deadlifts',
    matchKeys: ['deadlift', 'conventional deadlift', 'barbell deadlift', 'deficit deadlift'],
    movementPattern: 'hinge',
    workoutSplit: ['legs', 'lower', 'pull', 'back'],
    musclesFocused: { primary: ['gluteus maximus', 'hamstrings', 'erector spinae'], secondary: ['traps', 'forearms'] },
    hypertrophyRating: 10,
    fatLossRating: 9,
    enduranceRating: 5,
    timeRequired: 5,
    difficulty: 'advanced',
    jointFriendly: false,
    uniqueMuscleContribution: 'Total posterior chain overload — traps, back, glutes, hamstrings in one lift.',
    goalExplanation: goal(
      'Full posterior chain hypertrophy and strength.',
      'Highest systemic calorie burn per set.',
      'Moderate rep deadlifts for strength endurance.',
      'Maintains total-body pulling strength.',
      'Posterior chain anchor for recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '3-6', rest: 180 }),
    rotationGroup: 'posterior-chain-heavy',
  }),
  // Core
  e({
    wgerName: 'Plank',
    matchKeys: ['front plank', 'forearm plank'],
    movementPattern: 'carry',
    workoutSplit: ['core', 'full'],
    musclesFocused: { primary: ['rectus abdominis', 'transverse abdominis'], secondary: ['obliques'] },
    hypertrophyRating: 5,
    fatLossRating: 6,
    enduranceRating: 9,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Isometric anti-extension — foundational core stability.',
    goalExplanation: goal(
      'Core stability supports all compound lifts.',
      'Timed planks in conditioning blocks.',
      'Builds core endurance for sports.',
      'Low-fatigue core maintenance.',
      'Core stability during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '30-60 sec', rest: 45 },
      { sets: 3, reps: '45-90 sec', rest: 30 },
      { sets: 3, reps: '60-120 sec', rest: 30 },
    ),
    rotationGroup: 'core-stability',
  }),
  e({
    wgerName: 'Ab wheel',
    matchKeys: ['ab wheel rollout', 'ab roller'],
    movementPattern: 'carry',
    workoutSplit: ['core', 'full'],
    musclesFocused: { primary: ['rectus abdominis', 'transverse abdominis'], secondary: ['lats', 'shoulders'] },
    hypertrophyRating: 7,
    fatLossRating: 7,
    enduranceRating: 7,
    timeRequired: 3,
    difficulty: 'advanced',
    jointFriendly: false,
    uniqueMuscleContribution: 'Dynamic anti-extension under load — intense ab stretch and strength.',
    goalExplanation: goal(
      'Advanced ab hypertrophy and anti-extension strength.',
      'Ab wheel in metabolic core circuits.',
      'Moderate rep rollouts for core stamina.',
      'Challenging core maintenance.',
      'Core intensity during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '8-12', rest: 60 }),
    rotationGroup: 'core-stability',
  }),
  e({
    wgerName: 'Cable Crunch',
    matchKeys: ['crunches with cable', 'kneeling cable crunch'],
    movementPattern: 'isolation',
    workoutSplit: ['core'],
    musclesFocused: { primary: ['rectus abdominis'], secondary: [] },
    hypertrophyRating: 7,
    fatLossRating: 6,
    enduranceRating: 7,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Loadable spinal flexion — progressive ab hypertrophy.',
    goalExplanation: goal(
      'Weighted ab hypertrophy with cable tension.',
      'High rep crunches in core circuits.',
      'Ab endurance for athletes.',
      'Maintains ab thickness.',
      'Ab definition during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '12-15', rest: 45 }),
    rotationGroup: 'core-flexion',
  }),
  e({
    wgerName: 'Hanging Leg Raises',
    matchKeys: ['hanging leg raise'],
    movementPattern: 'isolation',
    workoutSplit: ['core'],
    musclesFocused: { primary: ['rectus abdominis', 'hip flexors'], secondary: ['obliques'] },
    hypertrophyRating: 8,
    fatLossRating: 7,
    enduranceRating: 8,
    timeRequired: 3,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Hanging position eliminates hip flexor cheat — lower ab emphasis.',
    goalExplanation: goal(
      'Lower ab development and grip/core integration.',
      'Leg raises in conditioning supersets.',
      'High rep hanging work builds core endurance.',
      'Functional core maintenance.',
      'Lower ab focus during recomp.',
    ),
    repRangeByGoal: reps({ sets: 3, reps: '10-15', rest: 60 }),
    rotationGroup: 'core-flexion',
  }),
  e({
    wgerName: 'Russian Twist',
    matchKeys: ['weighted russian twist'],
    movementPattern: 'isolation',
    workoutSplit: ['core'],
    musclesFocused: { primary: ['obliques'], secondary: ['rectus abdominis'] },
    hypertrophyRating: 6,
    fatLossRating: 7,
    enduranceRating: 8,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Rotational core work for oblique definition and athletic rotation.',
    goalExplanation: goal(
      'Oblique hypertrophy for tapered waist look.',
      'Russian twists in fat-loss core circuits.',
      'High rep rotation endurance.',
      'Maintains rotational core strength.',
      'Oblique detail during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '15-20', rest: 45 },
      { sets: 3, reps: '20-30', rest: 30 },
    ),
    rotationGroup: 'core-rotation',
  }),
  e({
    wgerName: 'Pallof Press',
    matchKeys: ['pallof press cable', 'anti rotation press'],
    movementPattern: 'carry',
    workoutSplit: ['core', 'full'],
    musclesFocused: { primary: ['obliques', 'transverse abdominis'], secondary: ['glutes'] },
    hypertrophyRating: 6,
    fatLossRating: 6,
    enduranceRating: 8,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Anti-rotation under load — trains core to resist twisting.',
    goalExplanation: goal(
      'Anti-rotation strength supports heavy compounds.',
      'Pallof holds in warm-ups and circuits.',
      'Isometric anti-rotation endurance.',
      'Injury-prevention core maintenance.',
      'Functional core during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '10-12 each side', rest: 45 },
      { sets: 3, reps: '12-15 each side', rest: 30 },
    ),
    rotationGroup: 'core-anti-rotation',
  }),
  e({
    wgerName: 'Deadbug',
    matchKeys: ['dead bug', 'dead bug exercise'],
    movementPattern: 'carry',
    workoutSplit: ['core', 'full'],
    musclesFocused: { primary: ['transverse abdominis', 'rectus abdominis'], secondary: ['obliques'] },
    hypertrophyRating: 5,
    fatLossRating: 6,
    enduranceRating: 8,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Supine anti-extension with limb coordination — low back friendly.',
    goalExplanation: goal(
      'Teaches bracing for squats and deadlifts.',
      'Dead bugs in warm-ups and active recovery.',
      'High rep coordination endurance.',
      'Gentle core maintenance.',
      'Core activation during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '10-12 each side', rest: 45 },
      { sets: 3, reps: '12-15 each side', rest: 30 },
    ),
    rotationGroup: 'core-stability',
  }),
  // Cardio / Conditioning
  e({
    wgerName: 'Battle Ropes',
    matchKeys: ['battle rope', 'battling ropes'],
    movementPattern: 'carry',
    workoutSplit: ['cardio', 'conditioning', 'full'],
    musclesFocused: { primary: ['shoulders', 'core'], secondary: ['forearms', 'legs'] },
    hypertrophyRating: 3,
    fatLossRating: 10,
    enduranceRating: 10,
    timeRequired: 2,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Full-body metabolic conditioning with upper-body power endurance.',
    goalExplanation: goal(
      'Accessory conditioning — not primary hypertrophy.',
      'Extreme calorie burn in short intervals.',
      'Builds work capacity and shoulder endurance.',
      'Low-impact conditioning maintenance.',
      'Metabolic boost during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: '20-30 sec', rest: 60 },
      { sets: 5, reps: '30-45 sec', rest: 45 },
      { sets: 6, reps: '45-60 sec', rest: 30 },
    ),
    rotationGroup: 'conditioning-rope',
  }),
  e({
    wgerName: 'box jumps',
    matchKeys: ['box jump', 'plyometric box jump'],
    movementPattern: 'squat',
    workoutSplit: ['cardio', 'conditioning', 'legs'],
    musclesFocused: { primary: ['quadriceps', 'gluteus maximus'], secondary: ['calves', 'core'] },
    hypertrophyRating: 4,
    fatLossRating: 9,
    enduranceRating: 8,
    timeRequired: 2,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Explosive power and plyometric calorie burn.',
    goalExplanation: goal(
      'Power development complements strength training.',
      'High-intensity intervals for fat loss.',
      'Plyometric endurance and athleticism.',
      'Maintain explosive leg power.',
      'Power intervals during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: '5-8', rest: 90 },
      { sets: 4, reps: '8-12', rest: 60 },
      { sets: 5, reps: '10-15', rest: 45 },
    ),
    rotationGroup: 'conditioning-plyo',
  }),
  e({
    wgerName: 'Burpee',
    matchKeys: ['burpees', '4-count burpees', '4-tel burpees'],
    movementPattern: 'squat',
    workoutSplit: ['cardio', 'conditioning', 'full'],
    musclesFocused: { primary: ['full body'], secondary: ['chest', 'quadriceps', 'core'] },
    hypertrophyRating: 3,
    fatLossRating: 10,
    enduranceRating: 10,
    timeRequired: 1,
    difficulty: 'intermediate',
    jointFriendly: false,
    uniqueMuscleContribution: 'Total-body metabolic movement — push, squat, and jump in one.',
    goalExplanation: goal(
      'Finisher volume only — not primary muscle builder.',
      'Maximum calorie burn per minute.',
      'Ultimate conditioning and work capacity.',
      'Minimal-equipment cardio maintenance.',
      'Metabolic finisher for recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '8-12', rest: 90 },
      { sets: 4, reps: '10-15', rest: 45 },
      { sets: 5, reps: '15-20', rest: 30 },
    ),
    rotationGroup: 'conditioning-bodyweight',
  }),
  e({
    wgerName: 'Jump rope: basic jumps',
    matchKeys: ['jump rope', 'skipping rope', 'rope skipping'],
    movementPattern: 'carry',
    workoutSplit: ['cardio', 'conditioning'],
    musclesFocused: { primary: ['calves', 'forearms'], secondary: ['shoulders', 'core'] },
    hypertrophyRating: 2,
    fatLossRating: 9,
    enduranceRating: 10,
    timeRequired: 2,
    difficulty: 'beginner',
    jointFriendly: true,
    uniqueMuscleContribution: 'Low-equipment steady-state or interval cardio with coordination.',
    goalExplanation: goal(
      'Active recovery — minimal hypertrophy stimulus.',
      'Efficient cardio for calorie deficit.',
      'Builds cardiovascular and calf endurance.',
      'Easy conditioning maintenance.',
      'Cardio support during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 3, reps: '60 sec', rest: 60 },
      { sets: 4, reps: '90 sec', rest: 45 },
      { sets: 5, reps: '2-3 min', rest: 30 },
    ),
    rotationGroup: 'conditioning-cardio',
  }),
  e({
    wgerName: 'Sled Push',
    matchKeys: ['prowler push', 'sled drag push'],
    movementPattern: 'carry',
    workoutSplit: ['cardio', 'conditioning', 'legs'],
    musclesFocused: { primary: ['quadriceps', 'gluteus maximus', 'calves'], secondary: ['core', 'shoulders'] },
    hypertrophyRating: 5,
    fatLossRating: 10,
    enduranceRating: 9,
    timeRequired: 3,
    difficulty: 'intermediate',
    jointFriendly: true,
    uniqueMuscleContribution: 'Concentric-only leg drive — high output with minimal eccentric soreness.',
    goalExplanation: goal(
      'Leg volume without heavy spinal load.',
      'Extreme metabolic leg conditioning.',
      'Work capacity and leg endurance.',
      'Joint-friendly leg conditioning.',
      'Metabolic leg work during recomp.',
    ),
    repRangeByGoal: reps(
      { sets: 4, reps: '20-30 m', rest: 90 },
      { sets: 5, reps: '30-40 m', rest: 60 },
      { sets: 6, reps: '40-50 m', rest: 45 },
    ),
    rotationGroup: 'conditioning-sled',
  }),
];

const smartLookup = new Map<string, ExerciseSmartData & { matchKeys?: string[] }>();
for (const entry of CURATED_EXERCISES) {
  smartLookup.set(normalizeExerciseName(entry.wgerName), entry);
  for (const key of entry.matchKeys ?? []) {
    smartLookup.set(normalizeExerciseName(key), entry);
  }
}

export function getSmartDataForName(name: string): ExerciseSmartData | null {
  const norm = normalizeExerciseName(name);
  const direct = smartLookup.get(norm);
  if (direct) return direct;
  return null;
}

export function listCuratedSmartData(): ExerciseSmartData[] {
  return CURATED_EXERCISES;
}

