import type { GroceryMealTemplate } from './grocery.js';

type Ingredient = GroceryMealTemplate['ingredients'][number];

const m = (
  id: string,
  name: string,
  slot: GroceryMealTemplate['slot'],
  costPerServing: number,
  servingsProduced: number,
  macros: { calories: number; protein: number; carbs: number; fat: number },
  proteinScore: number,
  ingredients: Ingredient[],
  instructions: string[],
): GroceryMealTemplate => ({
  id,
  name,
  slot,
  eligibleSlots: [slot],
  costPerServing,
  servingsProduced,
  macrosPerServing: macros,
  proteinScore,
  ingredients,
  instructions,
});

export const FALLBACK_GROCERY_MEALS: GroceryMealTemplate[] = [
  m(
    'scrambled-eggs-toast',
    'Scrambled eggs and toast',
    'breakfast',
    1.2,
    4,
    { calories: 320, protein: 18, carbs: 28, fat: 14 },
    7,
    [
      { key: 'eggs', displayName: 'Eggs', batchAmount: 0.67, unit: 'dozen', servingQuantity: '2 eggs' },
      { key: 'bread', displayName: 'Bread', batchAmount: 0.25, unit: 'loaf', servingQuantity: '1 slice' },
      { key: 'butter', displayName: 'Butter', batchAmount: 0.15, unit: 'pack', servingQuantity: '1 tsp' },
      { key: 'salt', displayName: 'Salt', batchAmount: 0.02, unit: 'container', servingQuantity: 'pinch' },
    ],
    [
      'Beat 2 eggs with a pinch of salt in a small bowl.',
      'Toast bread until golden on both sides.',
      'Melt butter in a nonstick pan over medium heat.',
      'Pour in eggs and stir gently until softly set, about 2 minutes.',
      'Butter the toast and serve with the scrambled eggs.',
    ],
  ),
  m(
    'oatmeal-banana',
    'Oatmeal with banana',
    'breakfast',
    0.8,
    2,
    { calories: 280, protein: 10, carbs: 48, fat: 6 },
    4,
    [
      { key: 'oats', displayName: 'Oats', batchAmount: 0.15, unit: 'container', servingQuantity: '½ cup dry' },
      { key: 'banana', displayName: 'Banana', batchAmount: 2, unit: 'each', servingQuantity: '1 medium' },
      { key: 'honey', displayName: 'Honey', batchAmount: 0.05, unit: 'jar', servingQuantity: '1 tbsp' },
      { key: 'milk', displayName: 'Milk', batchAmount: 0.15, unit: 'gallon', servingQuantity: '½ cup' },
    ],
    [
      'Bring milk and ½ cup water to a gentle simmer in a small pot.',
      'Stir in oats and cook over medium heat for 5 minutes, stirring often.',
      'Slice the banana while the oatmeal thickens.',
      'Remove from heat and stir in honey.',
      'Top with banana slices and serve warm.',
    ],
  ),
  m(
    'greek-yogurt-parfait',
    'Greek yogurt parfait',
    'breakfast',
    1.5,
    1,
    { calories: 260, protein: 20, carbs: 32, fat: 6 },
    8,
    [
      { key: 'greek yogurt', displayName: 'Greek yogurt', batchAmount: 1, unit: 'cup', servingQuantity: '1 cup' },
      { key: 'granola', displayName: 'Granola', batchAmount: 0.1, unit: 'bag', servingQuantity: '¼ cup' },
      { key: 'berries', displayName: 'Berries', batchAmount: 0.15, unit: 'bag', servingQuantity: '½ cup' },
    ],
    [
      'Add half the Greek yogurt to a bowl or jar.',
      'Sprinkle half the granola and berries on top.',
      'Add the remaining yogurt in a second layer.',
      'Finish with the rest of the granola and berries.',
      'Serve immediately or chill up to 30 minutes.',
    ],
  ),
  m(
    'egg-cheese-burrito',
    'Egg and cheese burrito',
    'breakfast',
    1.4,
    2,
    { calories: 380, protein: 22, carbs: 34, fat: 16 },
    7,
    [
      { key: 'eggs', displayName: 'Eggs', batchAmount: 0.33, unit: 'dozen', servingQuantity: '2 eggs' },
      { key: 'tortilla', displayName: 'Tortilla', batchAmount: 0.25, unit: 'pack', servingQuantity: '1 large' },
      { key: 'cheese', displayName: 'Cheese', batchAmount: 0.15, unit: 'block', servingQuantity: '¼ cup shredded' },
      { key: 'salsa', displayName: 'Salsa', batchAmount: 0.05, unit: 'jar', servingQuantity: '2 tbsp' },
    ],
    [
      'Scramble 2 eggs in a lightly oiled pan over medium heat.',
      'Warm the tortilla in a dry pan for 30 seconds per side.',
      'Place scrambled eggs in the center of the tortilla.',
      'Top with cheese and salsa.',
      'Fold the sides in and roll into a burrito.',
      'Optional: toast seam-side down for 1 minute to seal.',
    ],
  ),
  m(
    'peanut-butter-toast',
    'Peanut butter toast',
    'breakfast',
    0.9,
    1,
    { calories: 310, protein: 12, carbs: 36, fat: 14 },
    5,
    [
      { key: 'bread', displayName: 'Bread', batchAmount: 0.08, unit: 'loaf', servingQuantity: '2 slices' },
      { key: 'peanut butter', displayName: 'Peanut butter', batchAmount: 0.05, unit: 'jar', servingQuantity: '2 tbsp' },
      { key: 'banana', displayName: 'Banana', batchAmount: 1, unit: 'each', servingQuantity: '½ banana' },
    ],
    [
      'Toast bread until golden and crisp.',
      'Spread peanut butter evenly on both slices.',
      'Slice banana into thin rounds.',
      'Arrange banana on one slice and close the sandwich, or serve open-faced.',
      'Eat immediately while the toast is still warm.',
    ],
  ),
  m(
    'chicken-rice-bowl',
    'Chicken and rice bowl',
    'lunch',
    2.5,
    4,
    { calories: 420, protein: 38, carbs: 42, fat: 10 },
    9,
    [
      { key: 'chicken breast', displayName: 'Chicken breast', batchAmount: 1.2, unit: 'lb', servingQuantity: '5 oz' },
      { key: 'rice', displayName: 'Rice', batchAmount: 0.2, unit: 'bag', servingQuantity: '½ cup cooked' },
      { key: 'olive oil', displayName: 'Olive oil', batchAmount: 0.03, unit: 'bottle', servingQuantity: '1 tsp' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'salt', displayName: 'Salt', batchAmount: 0.02, unit: 'container', servingQuantity: 'pinch' },
    ],
    [
      'Cook rice according to package directions and keep warm.',
      'Season chicken with salt and mince the garlic.',
      'Heat olive oil in a skillet over medium-high heat.',
      'Cook chicken 6–7 minutes per side until done, then rest 3 minutes.',
      'Slice chicken and serve over rice with garlic sprinkled on top.',
    ],
  ),
  m(
    'turkey-sandwich',
    'Turkey sandwich',
    'lunch',
    2.0,
    1,
    { calories: 350, protein: 28, carbs: 32, fat: 12 },
    7,
    [
      { key: 'bread', displayName: 'Bread', batchAmount: 0.08, unit: 'loaf', servingQuantity: '2 slices' },
      { key: 'turkey deli', displayName: 'Turkey deli meat', batchAmount: 0.25, unit: 'pack', servingQuantity: '4 oz' },
      { key: 'cheese', displayName: 'Cheese', batchAmount: 0.08, unit: 'block', servingQuantity: '1 slice' },
      { key: 'mayo', displayName: 'Mayo', batchAmount: 0.03, unit: 'jar', servingQuantity: '1 tbsp' },
      { key: 'lettuce', displayName: 'Lettuce', batchAmount: 0.1, unit: 'head', servingQuantity: '2 leaves' },
    ],
    [
      'Lay out two slices of bread on a clean surface.',
      'Spread mayo evenly on both slices.',
      'Layer turkey and cheese on one slice.',
      'Add lettuce leaves and close the sandwich.',
      'Cut in half and serve.',
    ],
  ),
  m(
    'tuna-wrap',
    'Tuna salad wrap',
    'lunch',
    1.8,
    2,
    { calories: 340, protein: 26, carbs: 30, fat: 12 },
    8,
    [
      { key: 'tuna', displayName: 'Tuna', batchAmount: 2, unit: 'can', servingQuantity: '1 can' },
      { key: 'tortilla', displayName: 'Tortilla', batchAmount: 0.25, unit: 'pack', servingQuantity: '1 large' },
      { key: 'mayo', displayName: 'Mayo', batchAmount: 0.05, unit: 'jar', servingQuantity: '1 tbsp' },
      { key: 'celery', displayName: 'Celery', batchAmount: 0.2, unit: 'bunch', servingQuantity: '2 stalks diced' },
      { key: 'lettuce', displayName: 'Lettuce', batchAmount: 0.1, unit: 'head', servingQuantity: '1 leaf' },
    ],
    [
      'Drain tuna and flake into a bowl.',
      'Mix in mayo and diced celery until combined.',
      'Warm the tortilla briefly in a dry pan.',
      'Spread tuna salad down the center and top with lettuce.',
      'Fold sides in and roll tightly into a wrap.',
      'Slice in half and serve.',
    ],
  ),
  m(
    'black-bean-quesadilla',
    'Black bean quesadilla',
    'lunch',
    1.5,
    2,
    { calories: 360, protein: 16, carbs: 44, fat: 14 },
    5,
    [
      { key: 'tortilla', displayName: 'Tortilla', batchAmount: 0.25, unit: 'pack', servingQuantity: '2 large' },
      { key: 'black beans', displayName: 'Black beans', batchAmount: 1, unit: 'can', servingQuantity: '½ can' },
      { key: 'cheese', displayName: 'Cheese', batchAmount: 0.12, unit: 'block', servingQuantity: '⅓ cup shredded' },
      { key: 'salsa', displayName: 'Salsa', batchAmount: 0.05, unit: 'jar', servingQuantity: '2 tbsp' },
    ],
    [
      'Drain and rinse black beans, then mash lightly with a fork.',
      'Place one tortilla in a dry skillet over medium heat.',
      'Spread beans and cheese on the tortilla, then top with the second.',
      'Cook 2–3 minutes per side until golden and cheese melts.',
      'Cut into wedges and serve with salsa on the side.',
    ],
  ),
  m(
    'lentil-soup',
    'Lentil soup',
    'lunch',
    1.2,
    6,
    { calories: 280, protein: 18, carbs: 42, fat: 4 },
    6,
    [
      { key: 'lentils', displayName: 'Lentils', batchAmount: 0.25, unit: 'bag', servingQuantity: '⅓ cup dry' },
      { key: 'carrots', displayName: 'Carrots', batchAmount: 0.3, unit: 'bag', servingQuantity: '1 medium diced' },
      { key: 'celery', displayName: 'Celery', batchAmount: 0.25, unit: 'bunch', servingQuantity: '1 stalk diced' },
      { key: 'onion', displayName: 'Onion', batchAmount: 1, unit: 'each', servingQuantity: '¼ onion diced' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'broth', displayName: 'Broth', batchAmount: 0.5, unit: 'carton', servingQuantity: '1½ cups' },
    ],
    [
      'Dice carrot, celery, onion, and mince garlic.',
      'Sauté vegetables in a pot with a little oil for 5 minutes.',
      'Add lentils and broth, then bring to a boil.',
      'Reduce heat and simmer 25–30 minutes until lentils are tender.',
      'Season with salt and pepper to taste before serving.',
    ],
  ),
  m(
    'spaghetti-meat-sauce',
    'Spaghetti and meat sauce',
    'dinner',
    2.8,
    4,
    { calories: 520, protein: 32, carbs: 58, fat: 18 },
    7,
    [
      { key: 'pasta', displayName: 'Pasta', batchAmount: 0.5, unit: 'lb', servingQuantity: '2 oz dry' },
      { key: 'ground beef', displayName: 'Ground beef', batchAmount: 0.75, unit: 'lb', servingQuantity: '4 oz' },
      { key: 'tomato sauce', displayName: 'Tomato sauce', batchAmount: 0.5, unit: 'jar', servingQuantity: '½ cup' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'onion', displayName: 'Onion', batchAmount: 1, unit: 'each', servingQuantity: '¼ onion diced' },
    ],
    [
      'Boil pasta in salted water according to package directions.',
      'Dice onion and mince garlic while the pasta cooks.',
      'Brown ground beef with onion and garlic in a large pan.',
      'Drain excess fat and stir in tomato sauce.',
      'Simmer sauce 10 minutes, then toss with drained pasta.',
      'Serve hot with optional grated cheese.',
    ],
  ),
  m(
    'baked-chicken-thighs',
    'Baked chicken thighs and vegetables',
    'dinner',
    3.0,
    4,
    { calories: 450, protein: 36, carbs: 18, fat: 24 },
    8,
    [
      { key: 'chicken thighs', displayName: 'Chicken thighs', batchAmount: 1.5, unit: 'lb', servingQuantity: '1 thigh' },
      { key: 'broccoli', displayName: 'Broccoli', batchAmount: 1, unit: 'head', servingQuantity: '1 cup florets' },
      { key: 'olive oil', displayName: 'Olive oil', batchAmount: 0.04, unit: 'bottle', servingQuantity: '1 tbsp' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'salt', displayName: 'Salt', batchAmount: 0.02, unit: 'container', servingQuantity: 'pinch' },
    ],
    [
      'Preheat oven to 425°F and line a sheet pan.',
      'Toss broccoli with half the olive oil, minced garlic, and salt.',
      'Season chicken thighs with salt and remaining oil.',
      'Arrange chicken and broccoli on the pan without overcrowding.',
      'Roast 25–30 minutes until chicken reaches 165°F internally.',
      'Rest chicken 5 minutes before serving.',
    ],
  ),
  m(
    'beef-rice-stir-fry',
    'Beef and rice stir fry',
    'dinner',
    2.6,
    4,
    { calories: 480, protein: 30, carbs: 52, fat: 16 },
    7,
    [
      { key: 'ground beef', displayName: 'Ground beef', batchAmount: 0.75, unit: 'lb', servingQuantity: '4 oz' },
      { key: 'rice', displayName: 'Rice', batchAmount: 0.2, unit: 'bag', servingQuantity: '½ cup cooked' },
      { key: 'soy sauce', displayName: 'Soy sauce', batchAmount: 0.04, unit: 'bottle', servingQuantity: '1 tbsp' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'onion', displayName: 'Onion', batchAmount: 1, unit: 'each', servingQuantity: '¼ onion sliced' },
    ],
    [
      'Cook rice and keep warm.',
      'Heat a large skillet or wok over high heat.',
      'Brown ground beef, breaking it up as it cooks.',
      'Add sliced onion and minced garlic; stir-fry 2 minutes.',
      'Stir in soy sauce and cooked rice until heated through.',
      'Serve immediately.',
    ],
  ),
  m(
    'black-bean-tacos',
    'Black bean tacos',
    'dinner',
    1.8,
    3,
    { calories: 380, protein: 14, carbs: 48, fat: 14 },
    4,
    [
      { key: 'tortilla', displayName: 'Tortilla', batchAmount: 0.35, unit: 'pack', servingQuantity: '2 small' },
      { key: 'black beans', displayName: 'Black beans', batchAmount: 1.5, unit: 'can', servingQuantity: '½ can' },
      { key: 'cheese', displayName: 'Cheese', batchAmount: 0.15, unit: 'block', servingQuantity: '¼ cup shredded' },
      { key: 'salsa', displayName: 'Salsa', batchAmount: 0.08, unit: 'jar', servingQuantity: '2 tbsp' },
      { key: 'lettuce', displayName: 'Lettuce', batchAmount: 0.15, unit: 'head', servingQuantity: '½ cup shredded' },
    ],
    [
      'Drain and rinse black beans, then warm in a small pan.',
      'Heat tortillas in a dry skillet until pliable.',
      'Fill each tortilla with beans, cheese, and lettuce.',
      'Top with salsa and fold or roll to serve.',
      'Serve immediately while warm.',
    ],
  ),
  m(
    'chicken-soup',
    'Chicken soup',
    'dinner',
    2.2,
    6,
    { calories: 320, protein: 28, carbs: 32, fat: 8 },
    8,
    [
      { key: 'chicken breast', displayName: 'Chicken breast', batchAmount: 1.0, unit: 'lb', servingQuantity: '4 oz' },
      { key: 'broth', displayName: 'Broth', batchAmount: 1, unit: 'carton', servingQuantity: '1½ cups' },
      { key: 'carrots', displayName: 'Carrots', batchAmount: 0.3, unit: 'bag', servingQuantity: '1 medium sliced' },
      { key: 'celery', displayName: 'Celery', batchAmount: 0.25, unit: 'bunch', servingQuantity: '1 stalk sliced' },
      { key: 'onion', displayName: 'Onion', batchAmount: 1, unit: 'each', servingQuantity: '¼ onion diced' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'noodles', displayName: 'Noodles', batchAmount: 0.2, unit: 'bag', servingQuantity: '½ cup dry' },
    ],
    [
      'Dice carrot, celery, onion, and mince garlic.',
      'Simmer chicken in broth with vegetables for 15 minutes.',
      'Remove chicken, shred, and return to the pot.',
      'Add noodles and cook until tender, about 8 minutes.',
      'Season with salt and pepper and serve hot.',
    ],
  ),
  m(
    'baked-salmon-rice',
    'Baked salmon and rice',
    'dinner',
    4.0,
    2,
    { calories: 460, protein: 34, carbs: 38, fat: 18 },
    9,
    [
      { key: 'salmon', displayName: 'Salmon', batchAmount: 0.6, unit: 'lb', servingQuantity: '5 oz fillet' },
      { key: 'rice', displayName: 'Rice', batchAmount: 0.15, unit: 'bag', servingQuantity: '½ cup cooked' },
      { key: 'lemon', displayName: 'Lemon', batchAmount: 1, unit: 'each', servingQuantity: '2 wedges' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'olive oil', displayName: 'Olive oil', batchAmount: 0.03, unit: 'bottle', servingQuantity: '1 tsp' },
    ],
    [
      'Cook rice according to package directions.',
      'Preheat oven to 400°F and line a baking sheet.',
      'Place salmon on the sheet, drizzle with oil, and mince garlic on top.',
      'Bake 12–15 minutes until salmon flakes easily.',
      'Serve salmon over rice with lemon wedges squeezed on top.',
    ],
  ),
  m(
    'ground-turkey-sweet-potato',
    'Ground turkey and sweet potato',
    'dinner',
    3.2,
    4,
    { calories: 440, protein: 34, carbs: 36, fat: 16 },
    8,
    [
      { key: 'ground turkey', displayName: 'Ground turkey', batchAmount: 0.9, unit: 'lb', servingQuantity: '5 oz' },
      { key: 'sweet potato', displayName: 'Sweet potato', batchAmount: 4, unit: 'each', servingQuantity: '1 medium' },
      { key: 'olive oil', displayName: 'Olive oil', batchAmount: 0.03, unit: 'bottle', servingQuantity: '1 tsp' },
      { key: 'garlic', displayName: 'Garlic', batchAmount: 0.25, unit: 'head', servingQuantity: '2 cloves' },
      { key: 'onion', displayName: 'Onion', batchAmount: 1, unit: 'each', servingQuantity: '¼ onion diced' },
    ],
    [
      'Pierce sweet potato and microwave or bake until tender, about 8–12 minutes.',
      'Heat oil in a skillet over medium-high heat.',
      'Cook ground turkey with diced onion and garlic until browned.',
      'Season with salt and pepper to taste.',
      'Split sweet potato and top with turkey mixture.',
      'Serve immediately.',
    ],
  ),
];

/** @deprecated Use mealPool exports instead. */
export const GROCERY_MEALS = FALLBACK_GROCERY_MEALS;
